#!/bin/bash
#chmod +x <repo_root>/imp/tests/run-all-tests.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Running Full IMP System Test Suite..."

IMP_SAFE_TESTS="${IMP_SAFE_TESTS:-1}"

run_test() {
    local test_name="$1"
    if [[ "$IMP_SAFE_TESTS" == "1" ]]; then
        case "$test_name" in
            test-code-updater.py|test-self-healer.py|test-auto-heal.py|test-backup-restore.py|test-chained-workflow.py|test-auto-heal-script.py)
                echo "Skipping $test_name (IMP_SAFE_TESTS=1)"
                return 0
                ;;
        esac
    fi
    python3 "$SCRIPT_DIR/$test_name"
}

python3 "$SCRIPT_DIR/../logs/imp-log-manager.py"
run_test "test-core-functions.py"
run_test "test-learning-memory.py"
run_test "test-security.py"
run_test "test-session-guard.py"
run_test "test-zero-trust-assessor.py"
run_test "test-cyber-researcher.py"
run_test "test-poison-detector.py"
run_test "test-performance.py"
run_test "test-expansion.py"
run_test "test-load-scheduler.py"
run_test "test-self-improvement.py"
run_test "test-code-updater.py"
run_test "test-module-imports.py"
run_test "test-execute-pipeline.py"
run_test "test-processing-manager-validation.py"
run_test "test-processing-manager-register.py"
run_test "test-control-hub-plan.py"
run_test "test-control-hub-policy.py"
run_test "test-control-hub-queue.py"
run_test "test-operator-ui.py"
run_test "test-bin-access.py"
run_test "test-neural-network.py"
run_test "test-resource-nn.py"
run_test "test-neural-manager.py"
run_test "test-processing-manager.py"
run_test "test-processing-analytics.py"
run_test "test-processing-forecaster.py"
run_test "test-processing-security.py"
run_test "test-nn-menu.py"
run_test "test-network-task-nn.py"
run_test "test-network-task-trainer.py"
run_test "test-network-task-engine.py"
run_test "test-defense-nn.py"
run_test "test-defense-trainer.py"
run_test "test-defense-engine.py"
run_test "test-bbi-engine.py"
run_test "test-collaboratory-nn.py"
run_test "test-3d-network.py"
run_test "test-optimal-path.py"
run_test "test-adversarial-trainer.py"
run_test "test-model-analysis.py"
run_test "test-automated-defense.py"
run_test "test-hardware-guard.py"
run_test "test-firewall-manager.py"
run_test "test-intranet.py"
run_test "test-metacognition.py"
run_test "test-roadmap-checker.py"
run_test "test-module-operability.py"
run_test "test-config.py"
run_test "test-logs.py"
run_test "test-log-manager.py"
run_test "test-log-analyzer.py"
run_test "test-start-script.py"
run_test "test-stop-script.py"
run_test "test-install.py"
run_test "test-bug-hunter.py"
run_test "test-mode-advisor.py"
run_test "test-context-engine.py"
run_test "test-adaptive-planner.py"
run_test "test-message-bus.py"
run_test "test-goal-chat.py"
run_test "test-goal-manager.py"
run_test "test-control-hub.py"
run_test "test-node-communicator.py"
run_test "test-node-control.py"
run_test "test-operator-dashboard.py"
run_test "test-distributed-queue.py"
run_test "test-distributed-memory.py"
run_test "test-node-monitor.py"
run_test "test-secure-node-manager.py"
run_test "test-game-copilot.py"
run_test "test-coliseum-engine.py"
run_test "test-auth.py"
run_test "test-mood.py"
run_test "test-mood-cli.py"
run_test "test-motivation.py"
run_test "test-voice.py"
run_test "test-voice-menu.py"
run_test "test-speech.py"
run_test "test-tone-analyzer.py"
run_test "test-network-auditor.py"
run_test "test-cloud-orchestrator.py"
run_test "test-network-discovery.py"
run_test "test-network-monitor.py"
run_test "test-process-auditor.py"
run_test "test-incident-correlator.py"
run_test "test-identity-verifier.py"
run_test "test-identity-integration.py"
run_test "test-identity-toolkit.py"
run_test "test-windows-support.py"
run_test "test-blockchain-ledger.py"
run_test "test-self-healer.py"
run_test "test-auto-heal.py"
run_test "test-backup-restore.py"
run_test "test-chained-workflow.py"
run_test "test-autonomy-controller.py"
run_test "test-analysis-skill.py"
run_test "test-code-map.py"
run_test "test-debug-sandbox.py"
run_test "test-readiness-cli.py"
run_test "test-general-intelligence-review.py"
run_test "test-success-director.py"
run_test "test-chat-keepalive.py"
run_test "test-chat-verify.py"
run_test "test-auto-heal-script.py"
echo "All Tests Completed!"
